name: CI Security Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Bandit
        run: |
          pip install bandit
          bandit -r . -f json -o bandit-report.json

      - name: Fail if Bandit finds high severity issues
        run: |
          if grep '"issue_severity": "HIGH"' bandit-report.json; then
            echo "High severity issues found by Bandit."
            exit 1
          fi

      - name: Install Nuclei
        run: |
          curl -s https://api.github.com/repos/projectdiscovery/nuclei/releases/latest \
          | grep "browser_download_url.*linux_amd64.zip" \
          | cut -d : -f 2,3 \
          | tr -d \" \
          | wget -i - && unzip nuclei*.zip && sudo mv nuclei /usr/local/bin/

      - name: Run Nuclei static scan
        run: |
          nuclei -target app.py -file -type file -json -o nuclei-report.json

      - name: Fail if Nuclei finds any issues
        run: |
          if [ -s nuclei-report.json ]; then
            echo "Nuclei found issues in the code."
            cat nuclei-report.json
            exit 1
          fi

      - name: Build Docker image
        run: |
          docker build -t flask-vuln-app .

      - name: Run Container (Local deploy)
        run: |
          docker run -d -p 5000:5000 --name vulnapp flask-vuln-app
